import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Cinzel } from "next/font/google";

import MMModeProvider from "@/components/components/MMModeProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-cinzel",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
  lang="en"
  className={`
    ${geistSans.variable}
    ${geistMono.variable}
    ${cinzel.variable}
    h-full
    antialiased
  `}
>
<body className={`${inter.variable} min-h-full flex flex-col`}>
  <MMModeProvider>
    <div className="app-background">
      <div className="app-content">
        {children}
      </div>
    </div>
  </MMModeProvider>
</body>
</html>
  );
}
