import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Cinzel } from "next/font/google";

import MMModeProvider from "@/components/components/MMModeProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-cinzel",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
  lang="en"
  className={`
    ${geistSans.variable}
    ${geistMono.variable}
    ${cinzel.variable}
    h-full
    antialiased
  `}
>
<body className={`${inter.variable} min-h-full flex flex-col`}>
  <div
    className="app-background min-h-screen"
    style={{
      backgroundImage: `
        linear-gradient(
          rgba(7, 7, 7, 0.78),
          rgba(7, 7, 7, 0.90)
        ),
        url("/backgrounds/greek.jpg")
      `,
      backgroundSize: "cover",
      backgroundPosition: "center",
      backgroundRepeat: "no-repeat",
      backgroundAttachment: "fixed",
    }}
  >
    <MMModeProvider>
      {children}
    </MMModeProvider>
  </div>
</body>
</html>
  );
}
